baseURL = "/"
languageCode = "en-us"
title = "Refactor or Die"
publishDir = "public"
theme = "blank"
PygmentsCodeFences = true
pygmentsuseclasses = true
ignoreFiles = [ "new-post$", "serve$" ]

[author]
name = "Cole Lawrence"
email = "cole@colelawrence.com"
