version: 2
jobs:
  build:
    docker:
      - image: cibuilds/base:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: curl -L https://github.com/bep/s3deploy/releases/download/v2.0.1/s3deploy_2.0.1_Linux-64bit.tar.gz | tar xvz
      - run: curl -L https://github.com/gohugoio/hugo/releases/download/v0.56.0/hugo_0.56.0_Linux-64bit.tar.gz | tar xvz
      - run: HUGO_ENV=production ./hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: Run commands to see results on std-out in the circleci web gui log
          command: |
             pwd
             ./hugo env
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ./s3deploy -source=$HUGO_BUILD_DIR -region=us-east-1 -bucket=colel.dev -path=/
            else
              echo "Not master branch, dry run only"
            fi
